AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "AWS Marketplace Serverless SaaS Integration Application with Multi-Product Support"
Globals:
  Function:
    Timeout: 15
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Parameters:
  WebsiteS3BucketName:
    Type: String
    ConstraintDescription: "S3 bucket name must follow S3 recommendations https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html"
    Default: ""

  NewSubscribersTableName:
    Type: String
    AllowedPattern: ".*"
    Default: "AWSMarketplaceSubscribers"

  AWSMarketplaceMeteringRecordsTableName:
    Type: String
    AllowedPattern: ".*"
    Default: "AWSMarketplaceMeteringRecords"

  TypeOfSaaSListing:
    Type: String
    Default: contracts_with_subscription
    AllowedValues:
      - contracts_with_subscription
      - contracts
      - subscriptions

  SNSAccountID:
    Type: String
    Default: "287250355862"
    Description: "This is the AWS account hosting the SNS Entitlement and Subscription topics for your product."
    AllowedValues:
      - "287250355862"

  SNSRegion:
      Type: String
      Default: "us-east-1"
      Description: "This is the AWS region of the SNS Entitlement and Subscription topics for your product."
      AllowedValues: 
        - us-east-1

  ProductId:
    Type: String
    AllowedPattern: ".*"

  MarketplaceTechAdminEmail:
    Type: String
    AllowedPattern: ".*"

  MarketplaceSellerEmail:
    Type: String
    AllowedPattern: ".*"
    Default: ""

  CreateCrossAccountRole:
    Default: "false"
    Description: "Do you intend to use cross account access with this integration core?"
    Type: String
    AllowedValues:
      - "true"
      - "false"
  
  CrossAccountId:
    Default: ''
    Description: "Enter the cross AWS account id"
    Type: String

  CrossAccountRoleName: 
    Type: String
    Description: "Your Role Name (ex: OrganizationAccountAccessRole); This will need to be the same across all of the Member Accounts"

  CreateRegistrationWebPage:
    Default: "true"
    Type: String
    AllowedValues:
      - "true"
      - "false"

  UpdateFulfillmentURL:
    Default: "false"
    Type: String
    Description: "WARNING: This will update your product's fulfillment URL automatically. Be careful if your product is already public"
    AllowedValues:
      - "true"
      - "false"

Conditions:
  CreateEntitlementLogic:
    Fn::Or:
      - !Equals [!Ref TypeOfSaaSListing, contracts_with_subscription]
      - !Equals [!Ref TypeOfSaaSListing, contracts]

  CreateSubscriptionLogic:
    Fn::Or:
      - !Equals [!Ref TypeOfSaaSListing, contracts_with_subscription]
      - !Equals [!Ref TypeOfSaaSListing, subscriptions]

  CreateWeb: !Equals [!Ref CreateRegistrationWebPage, true]
  Buyernotificationemail: !Not [!Equals [!Ref MarketplaceSellerEmail, ""]]
  CreateCrossAccount: !Equals [!Ref CreateCrossAccountRole, true]
  UpdateFulfillment: !Equals [!Ref UpdateFulfillmentURL, true]

Resources:
  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      MethodSettings:
        - ResourcePath: /subscriber
          HttpMethod: POST, OPTIONS
        - ResourcePath: /redirectmarketplacetoken
          HttpMethod: POST, OPTIONS

  CrossAccountRoleForSaaSIntegration:
    Type: AWS::IAM::Role
    Condition: CreateCrossAccount
    DependsOn: 
     - AWSMarketplaceMeteringRecords 
     - AWSMarketplaceSubscribers
    Properties:
      RoleName:
         !Join
          - '-'
          - - 'CrossAccountRoleName'
            - !Select 
              - 0
              - !Split 
                - "-"
                - !Select
                  - 2
                  - !Split
                    - "/"
                    - !Ref AWS::StackId
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Join [":", ["arn:aws:iam:", !Ref CrossAccountId , "root"]]
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref CrossAccountRoleName
      Path: /
      Policies:
        - PolicyName:
           !Join
            - '-'
            - - 'CrossAccountPolicy'
              - !Select 
                - 0
                - !Split 
                  - "-"
                  - !Select
                    - 2
                    - !Split
                      - "/"
                      - !Ref AWS::StackId
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:UpdateItem'
                Resource:
                  - !GetAtt AWSMarketplaceMeteringRecords.Arn
                  - !GetAtt AWSMarketplaceSubscribers.Arn
                  
  # Updated DynamoDB table for multi-product support
  AWSMarketplaceMeteringRecords:
    Type: AWS::DynamoDB::Table
    Condition: CreateSubscriptionLogic
    Properties:
      AttributeDefinitions:
        - AttributeName: "productCode#customerIdentifier"
          AttributeType: "S"
        - AttributeName: "create_timestamp"
          AttributeType: "N"
        - AttributeName: "metering_pending"
          AttributeType: "S"
        - AttributeName: "customerIdentifier"
          AttributeType: "S"
        - AttributeName: "productCode"
          AttributeType: "S"

      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "productCode#customerIdentifier"
          KeyType: "HASH"
        - AttributeName: "create_timestamp"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: PendingMeteringRecordsIndex
          KeySchema:
            - AttributeName: "metering_pending"
              KeyType: "HASH"
            - AttributeName: "productCode"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: CustomerIdentifierIndex
          KeySchema:
            - AttributeName: "customerIdentifier"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
      TableName: !Ref AWSMarketplaceMeteringRecordsTableName

  # Updated DynamoDB table for multi-product support
  AWSMarketplaceSubscribers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "productCode#customerIdentifier"
          AttributeType: "S"
        - AttributeName: "customerIdentifier"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "productCode#customerIdentifier"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: CustomerIdentifierIndex
          KeySchema:
            - AttributeName: "customerIdentifier"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
      TableName: !Ref NewSubscribersTableName
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  
  RegisterNewMarketplaceCustomer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src-multiproduct/
      Handler: register-new-subscriber.registerNewSubscriber
      Runtime: nodejs22.x
      Environment:
        Variables:
          NewSubscribersTableName: !Ref NewSubscribersTableName
          EntitlementQueueUrl:
            !If [CreateEntitlementLogic, !Ref EntitlementSQSQueue, !Ref AWS::NoValue]
          MarketplaceSellerEmail:
            !If [Buyernotificationemail, !Ref MarketplaceSellerEmail, !Ref AWS::NoValue]
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref NewSubscribersTableName
        - Statement:
            - Sid: AWSMarketplaceResolveCustomer
              Effect: Allow
              Action:
                - aws-marketplace:ResolveCustomer
              Resource: "*"
        - !If
          - CreateEntitlementLogic
          - Statement:
              - Sid: SQSPolicy
                Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt EntitlementSQSQueue.Arn
          - !Ref "AWS::NoValue"

        - Statement:
            - Sid: Sendemail
              Effect: Allow
              Action:
                - ses:SendEmail
              Resource: "*"
      Events:
        RegisterCustomer:
          Type: Api
          Properties:
            Path: /subscriber
            Method: post
            RestApiId: !Ref ServerlessApi

  EntitlementSQSQueue:
    Type: AWS::SQS::Queue
    Condition: CreateEntitlementLogic

  EntitlementSQSHandler:
    Type: AWS::Serverless::Function
    Condition: CreateEntitlementLogic
    Properties:
      CodeUri: src-multiproduct/
      Handler: entitlement-sqs.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          NewSubscribersTableName: !Ref NewSubscribersTableName
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref NewSubscribersTableName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt EntitlementSQSQueue.Arn
        - Statement:
            - Sid: AWSMarketplaceEntitlements
              Effect: Allow
              Action:
                - aws-marketplace:GetEntitlements
              Resource: "*"
      Events:
        MySQSEvent:
          Type: SNS
          Properties:
            Topic:  !Sub 'arn:aws:sns:${SNSRegion}:${SNSAccountID}:aws-mp-entitlement-notification-${GetProductCode.ProductCode}'
            Region: !Sub '${SNSRegion}'
            SqsSubscription:
              BatchSize: 1
              QueueArn: !GetAtt EntitlementSQSQueue.Arn
              QueueUrl: !Ref EntitlementSQSQueue

  SubscriptionSQSHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src-multiproduct/
      Handler: subscription-sqs.SQSHandler
      Runtime: nodejs22.x
      Environment:
        Variables:
          NewSubscribersTableName: !Ref NewSubscribersTableName
          SupportSNSArn: !Ref SupportSNSTopic
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref NewSubscribersTableName
        - Statement:
            - Sid: SNSPublish
              Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref SupportSNSTopic
      Events:
        MySQSEvent:
          Type: SNS
          Properties:
            Topic:  !Sub 'arn:aws:sns:${SNSRegion}:${SNSAccountID}:aws-mp-subscription-notification-${GetProductCode.ProductCode}'
            Region: !Sub '${SNSRegion}'
            SqsSubscription: true

  SupportSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref MarketplaceTechAdminEmail
          Protocol: email

  GrantOrRevokeAccess:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src-multiproduct/
      Handler: grant-revoke-access-to-product.dynamodbStreamHandler
      Runtime: nodejs22.x
      Environment:
        Variables:
          SupportSNSArn: !Ref SupportSNSTopic
          LOG_LEVEL: "info"
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - Statement:
            - Sid: SNSPublish
              Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref SupportSNSTopic
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt AWSMarketplaceSubscribers.StreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON

  Hourly:
    Type: AWS::Serverless::Function
    Condition: CreateSubscriptionLogic
    Properties:
      CodeUri: src-multiproduct/
      Handler: metering-hourly-job.job
      Runtime: nodejs22.x
      Environment:
        Variables:
          SQSMeteringRecordsUrl: !Ref SQSMeteringRecords
          AWSMarketplaceMeteringRecordsTableName: !Ref AWSMarketplaceMeteringRecordsTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AWSMarketplaceMeteringRecordsTableName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SQSMeteringRecords.QueueName
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: "rate(1 hour)"
            Name:
             !Join
              - '-'
              - - 'MeteringSchedule'
                - !Select 
                  - 0
                  - !Split 
                    - "-"
                    - !Select
                      - 2
                      - !Split
                        - "/"
                        - !Ref AWS::StackId
            Description: SaaS Metering
            Enabled: true

  SQSMeteringRecords:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
       !Join
        - '-'
        - - !Select 
            - 0
            - !Split 
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref AWS::StackId
          - 'SQSMeteringRecords.fifo'
      ContentBasedDeduplication: true
      FifoQueue: true
      MessageRetentionPeriod: 3000
    Condition: CreateSubscriptionLogic

  MeteringSQSHandler:
    Type: AWS::Serverless::Function
    Condition: CreateSubscriptionLogic
    Properties:
      CodeUri: src-multiproduct/
      Handler: metering-sqs.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          AWSMarketplaceMeteringRecordsTableName: !Ref AWSMarketplaceMeteringRecordsTableName
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AWSMarketplaceMeteringRecordsTableName
        - Statement:
            - Sid: AWSMarketplaceMetering
              Effect: Allow
              Action:
                - aws-marketplace:BatchMeterUsage
              Resource: "*"
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSMeteringRecords.Arn
            BatchSize: 1

  # Rest of the template remains the same...
  # (Web hosting resources, Lambda functions, etc.)

  GetProductCode:
    Type: Custom::Lambda
    Properties:
      ServiceToken: !GetAtt GetProductCodeCustomResource.Arn
      ProductId: !Ref ProductId
      
  GetProductCodeCustomResource:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt CAPILambdasExecutionRole.Arn
      Runtime: nodejs22.x
      Handler: index.handler
      Code: 
        ZipFile: |
          const { MarketplaceCatalogClient, DescribeEntityCommand } = require("@aws-sdk/client-marketplace-catalog");
          const response = require('cfn-response');
          exports.handler = async (event, context) => {
          context.callbackWaitsForEmptyEventLoop = true;
            console.log("REQUEST RECEIVED:\n" + JSON.stringify(event));
            const client = new MarketplaceCatalogClient({ region: 'us-east-1' });
            const productId = event.ResourceProperties.ProductId; // Assuming the product ID is passed as an event parameter

            try {
                if (event.RequestType === 'Create' || event.RequestType === 'Update') {
                    // Fetch the product details from AWS Marketplace
                    const command = new DescribeEntityCommand({
                        Catalog: 'AWSMarketplace',
                        EntityId: productId,
                        EntityType: 'Product'
                    });
                    const resp = await client.send(command);

                    // Extract the product code from the response
                    const productCode = resp.DetailsDocument.Description.ProductCode;

                    const responseData = {
                        ProductCode: productCode
                    };

                    await response.send(event, context, 'SUCCESS', responseData);
                } else if (event.RequestType === 'Delete') {
                    // No action needed for delete
                    await response.send(event, context, 'SUCCESS', {});
                } else {
                    await response.send(event, context, 'FAILED', { error: 'Invalid request type' });
                }
            } catch (error) {
                console.error('Error:', error);
                await response.send(event, context, 'FAILED', { error: 'Failed to fetch product code' });
            }
          };

  CAPILambdasExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: manage-products
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "aws-marketplace:StartChangeSet"
                  - "aws-marketplace:DescribeEntity"
                Resource:
                  - !Sub "arn:${AWS::Partition}:aws-marketplace:us-east-1:${AWS::AccountId}:AWSMarketplace/SaaSProduct/${ProductId}"
                  - !Sub "arn:${AWS::Partition}:aws-marketplace:us-east-1:${AWS::AccountId}:AWSMarketplace/ChangeSet/*"

Outputs:
  CrossAccountRole:
    Description: This is the cross account role ARN.
    Value: 
      !If [
        CreateCrossAccount,
        !GetAtt CrossAccountRoleForSaaSIntegration.Arn,
        "N/A"
      ]

  SubscribersTableName:
    Description: DynamoDB table for storing subscriber information
    Value: !Ref AWSMarketplaceSubscribers

  MeteringRecordsTableName:
    Description: DynamoDB table for storing metering records
    Value: !If [
      CreateSubscriptionLogic,
      !Ref AWSMarketplaceMeteringRecords,
      "N/A"
    ]